channels:
  - conda-forge
dependencies:
  - r-base=4.1.0
  - r-irkernel=1.2 
  - r-mass=7.3_54
  - r-tidyverse=1.3.1
  - r-oce=1.4_0
  - r-seacarb=3.2.16
  - r-signal=0.7_7
  - r-ggpubr=0.4.0
  - r-sfsmisc=1.1_11
